// Writes supabase/seed.sql from the seed JSON in supabase/seed/. Run: npm run db:seed
// `supabase db reset` loads it after the migrations (local development only).
//
//  - three local staff accounts (sign in with a code sent to the local inbox, Mailpit)
//  - channels and tax rules
//  - every story as a working copy with its history; non-draft stories also published
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = fileURLToPath(new URL('../', import.meta.url))
const SEED = join(ROOT, 'supabase/seed')
const OUT = join(ROOT, 'supabase/seed.sql')

export const SEED_STAFF = [
  {
    id: '10000000-0000-4000-8000-000000000001',
    email: 'admin@tod.test',
    name: 'Туршилтын админ',
    role: 'admin',
  },
  {
    id: '10000000-0000-4000-8000-000000000002',
    email: 'editor@tod.test',
    name: 'Туршилтын редактор',
    role: 'editor',
  },
  {
    id: '10000000-0000-4000-8000-000000000003',
    email: 'reviewer@tod.test',
    name: 'Туршилтын хянагч',
    role: 'reviewer',
  },
] as const

const [, editor, reviewer] = SEED_STAFF

const readJson = (file: string): unknown =>
  JSON.parse(readFileSync(join(SEED, file), 'utf8'))

/** A dollar-quoted JSON literal; the tag never occurs in the seed text. */
function jsonb(value: unknown): string {
  const text = JSON.stringify(value)
  if (text.includes('$seed$')) throw new Error('seed text contains $seed$')
  return `$seed$${text}$seed$::jsonb`
}

const quote = (s: string) => `'${s.replaceAll("'", "''")}'`

function seedUser(u: (typeof SEED_STAFF)[number]): string {
  return `insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change,
  email_change_token_current, phone_change, phone_change_token, reauthentication_token
) values (
  '00000000-0000-0000-0000-000000000000', ${quote(u.id)}, 'authenticated', 'authenticated',
  ${quote(u.email)}, '', now(),
  '{"provider": "email", "providers": ["email"]}', '{}', now(), now(),
  '', '', '', '', '', '', '', ''
);
insert into auth.identities (provider_id, user_id, identity_data, provider, created_at, updated_at)
values (
  ${quote(u.id)}, ${quote(u.id)},
  jsonb_build_object('sub', ${quote(u.id)}, 'email', ${quote(u.email)}, 'email_verified', true),
  'email', now(), now()
);
insert into public.staff (user_id, name, role) values (${quote(u.id)}, ${quote(u.name)}, ${quote(u.role)});`
}

/**
 * A working copy with its history; published ones also get the public snapshot.
 * Seed statements are all parsed before any of them runs, so there is no helper function:
 * one self-contained block per story.
 */
function seedStory(doc: unknown, published: boolean, at: string): string {
  const publish = published
    ? `
  insert into public.story_revisions (story_id, content, action, author, created_at)
  values (story_id, doc, 'publish', ${quote(reviewer.id)}, at)
  returning id into revision;
  insert into public.published_stories
    (id, content, revision_id, first_published_at, published_at, published_by)
  values (story_id, private.published_content(doc), revision, at, at, ${quote(reviewer.id)});`
    : ''
  return `do $do$
declare
  doc jsonb := ${jsonb(doc)} - 'draft';
  story_id text := doc ->> 'id';
  at timestamptz := ${quote(at)};
  revision bigint;
begin
  insert into public.stories (id, content, state, created_by, created_at, updated_by, updated_at)
  values (
    story_id, doc, ${quote(published ? 'published' : 'draft')},
    ${quote(editor.id)}, at, ${quote(editor.id)}, at
  );
  insert into public.story_revisions (story_id, content, action, note, author, created_at)
  values (story_id, doc, 'import', 'supabase/seed', ${quote(editor.id)}, at);${publish}
end
$do$;`
}

const channels = readJson('channels.json') as { id: string }[]
const channelRows = channels.map(
  (c, i) => `  (${quote(c.id)}, ${i + 1}, ${jsonb(c)})`,
)

const stories = readdirSync(join(SEED, 'stories'))
  .filter((f) => f.endsWith('.json') && !f.startsWith('_'))
  .sort()
  .map((file) => {
    const doc = readJson(`stories/${file}`) as {
      draft?: boolean
      publishedAt?: string
    }
    // noon in Ulaanbaatar on the story's publication date
    const at = `${doc.publishedAt ?? '2026-01-01'} 12:00+08`
    return `-- ${file}\n${seedStory(doc, doc.draft !== true, at)}`
  })

const sql = `-- generated by scripts/gen-seed.ts — do not edit; run \`npm run db:seed\`
-- Local development data. Staff sign in at /admin with a code from the local inbox (Mailpit).

${SEED_STAFF.map(seedUser).join('\n\n')}

insert into public.channels (id, sort_order, content) values
${channelRows.join(',\n')};

insert into public.tax_rules (id, content) values ('pit', ${jsonb(readJson('taxRules.json'))});

-- the database reaches the edge functions through the gateway container on the Docker network
update public.settings
set site_url = 'http://localhost:5173',
    functions_url = 'http://supabase_kong_tod:8000/functions/v1';

${stories.join('\n\n')}
`

writeFileSync(OUT, sql)
console.log(
  `wrote supabase/seed.sql — ${SEED_STAFF.length} staff, ${channels.length} channels, ${stories.length} stories`,
)
