// Writes src/data/database.types.ts from the local database. Run: npm run db:types
// (needs `supabase start`). Pass --linked to generate from the linked project instead.
import { execFileSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const OUT = fileURLToPath(
  new URL('../src/data/database.types.ts', import.meta.url),
)
const target = process.argv.includes('--linked') ? '--linked' : '--local'

const types = execFileSync(
  'supabase',
  ['gen', 'types', 'typescript', target, '--schema', 'open'],
  { encoding: 'utf8', stdio: ['ignore', 'pipe', 'inherit'] },
)

writeFileSync(
  OUT,
  `// generated by scripts/gen-types.ts — do not edit; run \`npm run db:types\`\n\n${types.replace(/\r\n/g, '\n')}`,
)
console.log('wrote src/data/database.types.ts')
