// JSON Schemas generated from the zod contract in src/data/schema.ts. The database checks
// published stories, channels and tax rules against them (pg_jsonschema), so the database can
// never hold a document the site cannot render. Used by scripts/gen-json-schema.ts and the drift test.
import { z } from 'zod'
import {
  ChannelSchema,
  StorySchema,
  TaxRulesSchema,
} from '../src/data/schema.ts'

export const GENERATED_MARKER = '-- generated by scripts/gen-json-schema.ts'

// zod refinements (a real calendar date, trimmed text) have no JSON Schema form and are left out;
// the TypeScript validator and story_problems() cover them.
const toJson = (schema: z.ZodType) =>
  z.toJSONSchema(schema, { target: 'draft-7', unrepresentable: 'any' })

export const jsonSchemas = {
  story: toJson(StorySchema.omit({ draft: true })),
  channel: toJson(ChannelSchema),
  tax_rules: toJson(TaxRulesSchema),
}

export type SchemaName = keyof typeof jsonSchemas

/** SQL literal for a JSON value: single quotes doubled. */
function sqlJson(value: unknown): string {
  return `'${JSON.stringify(value).replaceAll("'", "''")}'::json`
}

/** The migration body: one immutable function per schema in the private schema. */
export function jsonSchemaMigration(): string {
  const fns = (Object.keys(jsonSchemas) as SchemaName[]).map(
    (name) => `create or replace function private.${name}_json_schema()
returns json
language sql
immutable
parallel safe
set search_path = ''
as $$ select ${sqlJson(jsonSchemas[name])} $$;`,
  )
  // check constraints run as the writing role (admins edit channels and tax rules directly)
  const grants = (Object.keys(jsonSchemas) as SchemaName[])
    .map(
      (name) =>
        `grant execute on function private.${name}_json_schema() to authenticated, service_role;`,
    )
    .join('\n')
  return `${GENERATED_MARKER} — do not edit; run \`npm run db:json-schema\`
-- JSON Schemas of the zod contract (src/data/schema.ts) for pg_jsonschema checks.

${fns.join('\n\n')}

${grants}
`
}

/** Pull the schema of one function back out of a generated migration (for the drift test). */
export function schemaFromMigration(sql: string, name: SchemaName): unknown {
  const m = new RegExp(
    `function private\\.${name}_json_schema\\(\\)[\\s\\S]*?select '([\\s\\S]*?)'::json \\$\\$`,
  ).exec(sql)
  if (!m) throw new Error(`no ${name}_json_schema() in the migration`)
  return JSON.parse(m[1].replaceAll("''", "'"))
}
