// The whole schema as one file for the Supabase dashboard's SQL editor, for setting up a project
// without the CLI (docs/SUPABASE_SETUP.md). Used by scripts/gen-sql-editor.ts and the drift test.

export const SCHEMA_FILE = 'supabase/setup/schema.sql'
export const GENERATED_MARKER = '-- generated by scripts/gen-sql-editor.ts'

export type Migration = { name: string; sql: string }

const RULE = `-- ${'='.repeat(95)}`

/** Every migration, in order, under a header that says how to run it and how to move to the CLI. */
export function schemaSql(migrations: Migration[]): string {
  const sorted = [...migrations].sort((a, b) => a.name.localeCompare(b.name))
  const versions = sorted.map((m) => m.name.split('_')[0]).join(' ')
  const parts = sorted.map(
    (m) =>
      `${RULE}\n-- supabase/migrations/${m.name}\n${RULE}\n\n${m.sql.trimEnd()}\n`,
  )
  return `${GENERATED_MARKER} — do not edit; run \`npm run db:sql-editor\`
-- The database of a NEW Supabase project, for the dashboard's SQL editor: every migration in
-- supabase/migrations/, in order. Step by step: docs/SUPABASE_SETUP.md.
--
-- Run it once, on an empty project. The editor runs the file as one transaction, so if it stops
-- with an error nothing is kept: fix the cause and run the whole file again. It only creates
-- things; the "delete" and "truncate" the editor may warn about are inside function bodies and
-- revoke statements.
--
-- If you later manage the database with the Supabase CLI (\`supabase db push\`), first record
-- these migrations as applied, so only newer ones run:
--   supabase migration repair --linked --status applied ${versions}

${parts.join('\n')}`
}
