// generated by scripts/gen-types.ts — do not edit; run `npm run db:types`

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      channels: {
        Row: {
          content: Json
          id: string
          sort_order: number
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          content: Json
          id: string
          sort_order?: number
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          content?: Json
          id?: string
          sort_order?: number
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      published_stories: {
        Row: {
          content: Json
          featured: boolean | null
          first_published_at: string
          groups: string[] | null
          id: string
          published_at: string
          published_by: string | null
          published_on: string | null
          revision_id: number
          search: unknown
          sort_order: number | null
          stage: string | null
          topics: string[] | null
          type: string | null
        }
        Insert: {
          content: Json
          featured?: boolean | null
          first_published_at?: string
          groups?: string[] | null
          id: string
          published_at?: string
          published_by?: string | null
          published_on?: string | null
          revision_id: number
          search?: unknown
          sort_order?: number | null
          stage?: string | null
          topics?: string[] | null
          type?: string | null
        }
        Update: {
          content?: Json
          featured?: boolean | null
          first_published_at?: string
          groups?: string[] | null
          id?: string
          published_at?: string
          published_by?: string | null
          published_on?: string | null
          revision_id?: number
          search?: unknown
          sort_order?: number | null
          stage?: string | null
          topics?: string[] | null
          type?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "published_stories_id_fkey"
            columns: ["id"]
            isOneToOne: true
            referencedRelation: "stories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "published_stories_id_fkey"
            columns: ["id"]
            isOneToOne: true
            referencedRelation: "story_admin_list"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "published_stories_revision_id_fkey"
            columns: ["revision_id"]
            isOneToOne: false
            referencedRelation: "story_revisions"
            referencedColumns: ["id"]
          },
        ]
      }
      settings: {
        Row: {
          deploy_hook_url: string | null
          functions_url: string | null
          id: boolean
          require_two_person_review: boolean
          site_url: string | null
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          deploy_hook_url?: string | null
          functions_url?: string | null
          id?: boolean
          require_two_person_review?: boolean
          site_url?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          deploy_hook_url?: string | null
          functions_url?: string | null
          id?: boolean
          require_two_person_review?: boolean
          site_url?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      staff: {
        Row: {
          created_at: string
          name: string
          role: Database["public"]["Enums"]["staff_role"]
          user_id: string
        }
        Insert: {
          created_at?: string
          name: string
          role: Database["public"]["Enums"]["staff_role"]
          user_id: string
        }
        Update: {
          created_at?: string
          name?: string
          role?: Database["public"]["Enums"]["staff_role"]
          user_id?: string
        }
        Relationships: []
      }
      stories: {
        Row: {
          content: Json
          created_at: string
          created_by: string | null
          id: string
          review_note: string | null
          state: Database["public"]["Enums"]["story_state"]
          submitted_at: string | null
          submitted_by: string | null
          updated_at: string
          updated_by: string | null
          version: number
        }
        Insert: {
          content: Json
          created_at?: string
          created_by?: string | null
          id: string
          review_note?: string | null
          state?: Database["public"]["Enums"]["story_state"]
          submitted_at?: string | null
          submitted_by?: string | null
          updated_at?: string
          updated_by?: string | null
          version?: number
        }
        Update: {
          content?: Json
          created_at?: string
          created_by?: string | null
          id?: string
          review_note?: string | null
          state?: Database["public"]["Enums"]["story_state"]
          submitted_at?: string | null
          submitted_by?: string | null
          updated_at?: string
          updated_by?: string | null
          version?: number
        }
        Relationships: []
      }
      story_revisions: {
        Row: {
          action: Database["public"]["Enums"]["revision_action"]
          author: string | null
          content: Json
          created_at: string
          id: number
          note: string | null
          story_id: string
        }
        Insert: {
          action: Database["public"]["Enums"]["revision_action"]
          author?: string | null
          content: Json
          created_at?: string
          id?: never
          note?: string | null
          story_id: string
        }
        Update: {
          action?: Database["public"]["Enums"]["revision_action"]
          author?: string | null
          content?: Json
          created_at?: string
          id?: never
          note?: string | null
          story_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "story_revisions_story_id_fkey"
            columns: ["story_id"]
            isOneToOne: false
            referencedRelation: "stories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "story_revisions_story_id_fkey"
            columns: ["story_id"]
            isOneToOne: false
            referencedRelation: "story_admin_list"
            referencedColumns: ["id"]
          },
        ]
      }
      tax_rules: {
        Row: {
          content: Json
          id: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          content: Json
          id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          content?: Json
          id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      story_admin_list: {
        Row: {
          created_at: string | null
          first_published_at: string | null
          id: string | null
          is_live: boolean | null
          published_at: string | null
          review_note: string | null
          stage: string | null
          state: Database["public"]["Enums"]["story_state"] | null
          submitted_at: string | null
          submitted_by_name: string | null
          title: string | null
          todo_count: number | null
          type: string | null
          updated_at: string | null
          updated_by: string | null
          updated_by_name: string | null
          version: number | null
        }
        Relationships: []
      }
      story_cards: {
        Row: {
          featured: boolean | null
          groups: string[] | null
          id: string | null
          published_on: string | null
          sort_order: number | null
          source_count: number | null
          stage: string | null
          summary: Json | null
          timeline: Json | null
          title: string | null
          topics: string[] | null
          type: string | null
        }
        Insert: {
          featured?: boolean | null
          groups?: string[] | null
          id?: string | null
          published_on?: string | null
          sort_order?: number | null
          source_count?: never
          stage?: string | null
          summary?: never
          timeline?: never
          title?: never
          topics?: string[] | null
          type?: string | null
        }
        Update: {
          featured?: boolean | null
          groups?: string[] | null
          id?: string | null
          published_on?: string | null
          sort_order?: number | null
          source_count?: never
          stage?: string | null
          summary?: never
          timeline?: never
          title?: never
          topics?: string[] | null
          type?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "published_stories_id_fkey"
            columns: ["id"]
            isOneToOne: true
            referencedRelation: "stories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "published_stories_id_fkey"
            columns: ["id"]
            isOneToOne: true
            referencedRelation: "story_admin_list"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      create_story: {
        Args: {
          p_action?: Database["public"]["Enums"]["revision_action"]
          p_content: Json
          p_id: string
        }
        Returns: {
          content: Json
          created_at: string
          created_by: string | null
          id: string
          review_note: string | null
          state: Database["public"]["Enums"]["story_state"]
          submitted_at: string | null
          submitted_by: string | null
          updated_at: string
          updated_by: string | null
          version: number
        }
        SetofOptions: {
          from: "*"
          to: "stories"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      delete_story: { Args: { p_id: string }; Returns: undefined }
      get_channels: { Args: never; Returns: Json }
      get_tax_rules: { Args: never; Returns: Json }
      list_staff: {
        Args: never
        Returns: {
          created_at: string
          email: string
          last_sign_in_at: string
          name: string
          role: Database["public"]["Enums"]["staff_role"]
          user_id: string
        }[]
      }
      publish_story: {
        Args: {
          p_correction?: string
          p_id: string
          p_note?: string
          p_version: number
        }
        Returns: {
          content: Json
          featured: boolean | null
          first_published_at: string
          groups: string[] | null
          id: string
          published_at: string
          published_by: string | null
          published_on: string | null
          revision_id: number
          search: unknown
          sort_order: number | null
          stage: string | null
          topics: string[] | null
          type: string | null
        }
        SetofOptions: {
          from: "*"
          to: "published_stories"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      remove_staff: { Args: { p_user_id: string }; Returns: undefined }
      request_changes: {
        Args: { p_id: string; p_note: string; p_version: number }
        Returns: {
          content: Json
          created_at: string
          created_by: string | null
          id: string
          review_note: string | null
          state: Database["public"]["Enums"]["story_state"]
          submitted_at: string | null
          submitted_by: string | null
          updated_at: string
          updated_by: string | null
          version: number
        }
        SetofOptions: {
          from: "*"
          to: "stories"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      restore_revision: {
        Args: { p_revision_id: number; p_version: number }
        Returns: {
          content: Json
          created_at: string
          created_by: string | null
          id: string
          review_note: string | null
          state: Database["public"]["Enums"]["story_state"]
          submitted_at: string | null
          submitted_by: string | null
          updated_at: string
          updated_by: string | null
          version: number
        }
        SetofOptions: {
          from: "*"
          to: "stories"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      save_story: {
        Args: { p_content: Json; p_id: string; p_version: number }
        Returns: {
          content: Json
          created_at: string
          created_by: string | null
          id: string
          review_note: string | null
          state: Database["public"]["Enums"]["story_state"]
          submitted_at: string | null
          submitted_by: string | null
          updated_at: string
          updated_by: string | null
          version: number
        }
        SetofOptions: {
          from: "*"
          to: "stories"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      set_staff_role: {
        Args: {
          p_role: Database["public"]["Enums"]["staff_role"]
          p_user_id: string
        }
        Returns: undefined
      }
      story_problems: { Args: { p_content: Json }; Returns: string[] }
      submit_story: {
        Args: { p_id: string; p_note?: string; p_version: number }
        Returns: {
          content: Json
          created_at: string
          created_by: string | null
          id: string
          review_note: string | null
          state: Database["public"]["Enums"]["story_state"]
          submitted_at: string | null
          submitted_by: string | null
          updated_at: string
          updated_by: string | null
          version: number
        }
        SetofOptions: {
          from: "*"
          to: "stories"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      unpublish_story: {
        Args: { p_id: string; p_note: string; p_version: number }
        Returns: {
          content: Json
          created_at: string
          created_by: string | null
          id: string
          review_note: string | null
          state: Database["public"]["Enums"]["story_state"]
          submitted_at: string | null
          submitted_by: string | null
          updated_at: string
          updated_by: string | null
          version: number
        }
        SetofOptions: {
          from: "*"
          to: "stories"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      update_my_name: { Args: { p_name: string }; Returns: undefined }
    }
    Enums: {
      revision_action:
        | "create"
        | "import"
        | "ai_draft"
        | "save"
        | "restore"
        | "submit"
        | "request_changes"
        | "publish"
        | "unpublish"
      staff_role: "editor" | "reviewer" | "admin"
      story_state: "draft" | "in_review" | "changes_requested" | "published"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      revision_action: [
        "create",
        "import",
        "ai_draft",
        "save",
        "restore",
        "submit",
        "request_changes",
        "publish",
        "unpublish",
      ],
      staff_role: ["editor", "reviewer", "admin"],
      story_state: ["draft", "in_review", "changes_requested", "published"],
    },
  },
} as const

